// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/approval_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/approval_repository.go -destination=internal/repository/mocks/approval_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApprovalRepository is a mock of ApprovalRepository interface.
type MockApprovalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalRepositoryMockRecorder
	isgomock struct{}
}

// MockApprovalRepositoryMockRecorder is the mock recorder for MockApprovalRepository.
type MockApprovalRepositoryMockRecorder struct {
	mock *MockApprovalRepository
}

// NewMockApprovalRepository creates a new mock instance.
func NewMockApprovalRepository(ctrl *gomock.Controller) *MockApprovalRepository {
	mock := &MockApprovalRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalRepository) EXPECT() *MockApprovalRepositoryMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockApprovalRepository) Approve(ctx context.Context, shopID, requestID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, shopID, requestID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockApprovalRepositoryMockRecorder) Approve(ctx, shopID, requestID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockApprovalRepository)(nil).Approve), ctx, shopID, requestID, reviewerID)
}

// ListByBarber mocks base method.
func (m *MockApprovalRepository) ListByBarber(ctx context.Context, barberID string) ([]models.ApprovalRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBarber", ctx, barberID)
	ret0, _ := ret[0].([]models.ApprovalRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBarber indicates an expected call of ListByBarber.
func (mr *MockApprovalRepositoryMockRecorder) ListByBarber(ctx, barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBarber", reflect.TypeOf((*MockApprovalRepository)(nil).ListByBarber), ctx, barberID)
}

// ListPending mocks base method.
func (m *MockApprovalRepository) ListPending(ctx context.Context, shopID string) ([]models.ApprovalRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, shopID)
	ret0, _ := ret[0].([]models.ApprovalRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockApprovalRepositoryMockRecorder) ListPending(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockApprovalRepository)(nil).ListPending), ctx, shopID)
}

// Reject mocks base method.
func (m *MockApprovalRepository) Reject(ctx context.Context, shopID, requestID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, shopID, requestID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockApprovalRepositoryMockRecorder) Reject(ctx, shopID, requestID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockApprovalRepository)(nil).Reject), ctx, shopID, requestID, reviewerID)
}
