// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/barber_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/barber_repository.go -destination=internal/repository/mocks/barber_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBarberRepository is a mock of BarberRepository interface.
type MockBarberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBarberRepositoryMockRecorder
	isgomock struct{}
}

// MockBarberRepositoryMockRecorder is the mock recorder for MockBarberRepository.
type MockBarberRepositoryMockRecorder struct {
	mock *MockBarberRepository
}

// NewMockBarberRepository creates a new mock instance.
func NewMockBarberRepository(ctrl *gomock.Controller) *MockBarberRepository {
	mock := &MockBarberRepository{ctrl: ctrl}
	mock.recorder = &MockBarberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarberRepository) EXPECT() *MockBarberRepositoryMockRecorder {
	return m.recorder
}

// CreateBarberProfile mocks base method.
func (m *MockBarberRepository) CreateBarberProfile(ctx context.Context, userID, bio string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBarberProfile", ctx, userID, bio)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBarberProfile indicates an expected call of CreateBarberProfile.
func (mr *MockBarberRepositoryMockRecorder) CreateBarberProfile(ctx, userID, bio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBarberProfile", reflect.TypeOf((*MockBarberRepository)(nil).CreateBarberProfile), ctx, userID, bio)
}

// GetBarberProfile mocks base method.
func (m *MockBarberRepository) GetBarberProfile(ctx context.Context, barberID string) (*models.BarberWithProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarberProfile", ctx, barberID)
	ret0, _ := ret[0].(*models.BarberWithProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarberProfile indicates an expected call of GetBarberProfile.
func (mr *MockBarberRepositoryMockRecorder) GetBarberProfile(ctx, barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarberProfile", reflect.TypeOf((*MockBarberRepository)(nil).GetBarberProfile), ctx, barberID)
}

// ListActiveBarbers mocks base method.
func (m *MockBarberRepository) ListActiveBarbers(ctx context.Context, shopID string) ([]models.BarberWithProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveBarbers", ctx, shopID)
	ret0, _ := ret[0].([]models.BarberWithProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveBarbers indicates an expected call of ListActiveBarbers.
func (mr *MockBarberRepositoryMockRecorder) ListActiveBarbers(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveBarbers", reflect.TypeOf((*MockBarberRepository)(nil).ListActiveBarbers), ctx, shopID)
}

// RecalculateAvgRating mocks base method.
func (m *MockBarberRepository) RecalculateAvgRating(ctx context.Context, tx pgx.Tx, barberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculateAvgRating", ctx, tx, barberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalculateAvgRating indicates an expected call of RecalculateAvgRating.
func (mr *MockBarberRepositoryMockRecorder) RecalculateAvgRating(ctx, tx, barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateAvgRating", reflect.TypeOf((*MockBarberRepository)(nil).RecalculateAvgRating), ctx, tx, barberID)
}

// SetActive mocks base method.
func (m *MockBarberRepository) SetActive(ctx context.Context, barberID, shopID string, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, barberID, shopID, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockBarberRepositoryMockRecorder) SetActive(ctx, barberID, shopID, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockBarberRepository)(nil).SetActive), ctx, barberID, shopID, active)
}

// UpdateBio mocks base method.
func (m *MockBarberRepository) UpdateBio(ctx context.Context, barberID, bio string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBio", ctx, barberID, bio)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBio indicates an expected call of UpdateBio.
func (mr *MockBarberRepositoryMockRecorder) UpdateBio(ctx, barberID, bio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBio", reflect.TypeOf((*MockBarberRepository)(nil).UpdateBio), ctx, barberID, bio)
}
