// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/rating_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/rating_repository.go -destination=internal/repository/mocks/rating_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
	isgomock struct{}
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// CreateRating mocks base method.
func (m *MockRatingRepository) CreateRating(ctx context.Context, in models.RatingCreateInput) (*models.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRating", ctx, in)
	ret0, _ := ret[0].(*models.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRating indicates an expected call of CreateRating.
func (mr *MockRatingRepositoryMockRecorder) CreateRating(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRating", reflect.TypeOf((*MockRatingRepository)(nil).CreateRating), ctx, in)
}

// ListForBarber mocks base method.
func (m *MockRatingRepository) ListForBarber(ctx context.Context, barberID string, page, pageSize int) ([]models.Rating, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForBarber", ctx, barberID, page, pageSize)
	ret0, _ := ret[0].([]models.Rating)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListForBarber indicates an expected call of ListForBarber.
func (mr *MockRatingRepositoryMockRecorder) ListForBarber(ctx, barberID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForBarber", reflect.TypeOf((*MockRatingRepository)(nil).ListForBarber), ctx, barberID, page, pageSize)
}
