// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/reservation_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/reservation_repository.go -destination=internal/repository/mocks/reservation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockReservationRepository) Cancel(ctx context.Context, id, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockReservationRepositoryMockRecorder) Cancel(ctx, id, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockReservationRepository)(nil).Cancel), ctx, id, customerID)
}

// CreateReservation mocks base method.
func (m *MockReservationRepository) CreateReservation(ctx context.Context, in models.ReservationCreateInput) (*models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservation", ctx, in)
	ret0, _ := ret[0].(*models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReservation indicates an expected call of CreateReservation.
func (mr *MockReservationRepositoryMockRecorder) CreateReservation(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservation", reflect.TypeOf((*MockReservationRepository)(nil).CreateReservation), ctx, in)
}

// GetReservation mocks base method.
func (m *MockReservationRepository) GetReservation(ctx context.Context, id string) (*models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservation", ctx, id)
	ret0, _ := ret[0].(*models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservation indicates an expected call of GetReservation.
func (mr *MockReservationRepositoryMockRecorder) GetReservation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservation", reflect.TypeOf((*MockReservationRepository)(nil).GetReservation), ctx, id)
}

// ListForBarber mocks base method.
func (m *MockReservationRepository) ListForBarber(ctx context.Context, barberID string, from, to time.Time) ([]models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForBarber", ctx, barberID, from, to)
	ret0, _ := ret[0].([]models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForBarber indicates an expected call of ListForBarber.
func (mr *MockReservationRepositoryMockRecorder) ListForBarber(ctx, barberID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForBarber", reflect.TypeOf((*MockReservationRepository)(nil).ListForBarber), ctx, barberID, from, to)
}

// ListForCustomer mocks base method.
func (m *MockReservationRepository) ListForCustomer(ctx context.Context, customerID string) ([]models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForCustomer", ctx, customerID)
	ret0, _ := ret[0].([]models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForCustomer indicates an expected call of ListForCustomer.
func (mr *MockReservationRepositoryMockRecorder) ListForCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForCustomer", reflect.TypeOf((*MockReservationRepository)(nil).ListForCustomer), ctx, customerID)
}

// ListForShop mocks base method.
func (m *MockReservationRepository) ListForShop(ctx context.Context, shopID string, filter models.ReservationFilter) ([]models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForShop", ctx, shopID, filter)
	ret0, _ := ret[0].([]models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForShop indicates an expected call of ListForShop.
func (mr *MockReservationRepositoryMockRecorder) ListForShop(ctx, shopID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForShop", reflect.TypeOf((*MockReservationRepository)(nil).ListForShop), ctx, shopID, filter)
}

// UpdateStatus mocks base method.
func (m *MockReservationRepository) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockReservationRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockReservationRepository)(nil).UpdateStatus), ctx, id, status)
}
