// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/schedule_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/schedule_repository.go -destination=internal/repository/mocks/schedule_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// AddException mocks base method.
func (m *MockScheduleRepository) AddException(ctx context.Context, barberID string, in models.ScheduleExceptionInput) (*models.ScheduleException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddException", ctx, barberID, in)
	ret0, _ := ret[0].(*models.ScheduleException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddException indicates an expected call of AddException.
func (mr *MockScheduleRepositoryMockRecorder) AddException(ctx, barberID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddException", reflect.TypeOf((*MockScheduleRepository)(nil).AddException), ctx, barberID, in)
}

// ApplySchedule mocks base method.
func (m *MockScheduleRepository) ApplySchedule(ctx context.Context, tx pgx.Tx, barberID string, payload json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySchedule", ctx, tx, barberID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySchedule indicates an expected call of ApplySchedule.
func (mr *MockScheduleRepositoryMockRecorder) ApplySchedule(ctx, tx, barberID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySchedule", reflect.TypeOf((*MockScheduleRepository)(nil).ApplySchedule), ctx, tx, barberID, payload)
}

// GetApprovedSchedule mocks base method.
func (m *MockScheduleRepository) GetApprovedSchedule(ctx context.Context, barberID string) ([]models.WorkSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedSchedule", ctx, barberID)
	ret0, _ := ret[0].([]models.WorkSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovedSchedule indicates an expected call of GetApprovedSchedule.
func (mr *MockScheduleRepositoryMockRecorder) GetApprovedSchedule(ctx, barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).GetApprovedSchedule), ctx, barberID)
}

// GetException mocks base method.
func (m *MockScheduleRepository) GetException(ctx context.Context, barberID string, date time.Time) (*models.ScheduleException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetException", ctx, barberID, date)
	ret0, _ := ret[0].(*models.ScheduleException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetException indicates an expected call of GetException.
func (mr *MockScheduleRepositoryMockRecorder) GetException(ctx, barberID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetException", reflect.TypeOf((*MockScheduleRepository)(nil).GetException), ctx, barberID, date)
}

// ProposeSchedule mocks base method.
func (m *MockScheduleRepository) ProposeSchedule(ctx context.Context, shopID, barberID string, in models.ScheduleUpdateInput) (*models.ApprovalRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposeSchedule", ctx, shopID, barberID, in)
	ret0, _ := ret[0].(*models.ApprovalRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProposeSchedule indicates an expected call of ProposeSchedule.
func (mr *MockScheduleRepositoryMockRecorder) ProposeSchedule(ctx, shopID, barberID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).ProposeSchedule), ctx, shopID, barberID, in)
}
