// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/service_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/service_repository.go -destination=internal/repository/mocks/service_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	json "encoding/json"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRepository is a mock of ServiceRepository interface.
type MockServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceRepositoryMockRecorder is the mock recorder for MockServiceRepository.
type MockServiceRepositoryMockRecorder struct {
	mock *MockServiceRepository
}

// NewMockServiceRepository creates a new mock instance.
func NewMockServiceRepository(ctrl *gomock.Controller) *MockServiceRepository {
	mock := &MockServiceRepository{ctrl: ctrl}
	mock.recorder = &MockServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRepository) EXPECT() *MockServiceRepositoryMockRecorder {
	return m.recorder
}

// ApplyUpdate mocks base method.
func (m *MockServiceRepository) ApplyUpdate(ctx context.Context, tx pgx.Tx, serviceID string, payload json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyUpdate", ctx, tx, serviceID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyUpdate indicates an expected call of ApplyUpdate.
func (mr *MockServiceRepositoryMockRecorder) ApplyUpdate(ctx, tx, serviceID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyUpdate", reflect.TypeOf((*MockServiceRepository)(nil).ApplyUpdate), ctx, tx, serviceID, payload)
}

// CreateService mocks base method.
func (m *MockServiceRepository) CreateService(ctx context.Context, shopID string, in models.ServiceCreateInput) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", ctx, shopID, in)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockServiceRepositoryMockRecorder) CreateService(ctx, shopID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockServiceRepository)(nil).CreateService), ctx, shopID, in)
}

// GetService mocks base method.
func (m *MockServiceRepository) GetService(ctx context.Context, id string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, id)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockServiceRepositoryMockRecorder) GetService(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockServiceRepository)(nil).GetService), ctx, id)
}

// ListServices mocks base method.
func (m *MockServiceRepository) ListServices(ctx context.Context, shopID string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices", ctx, shopID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockServiceRepositoryMockRecorder) ListServices(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockServiceRepository)(nil).ListServices), ctx, shopID)
}

// ListServicesByBarber mocks base method.
func (m *MockServiceRepository) ListServicesByBarber(ctx context.Context, barberID string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesByBarber", ctx, barberID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesByBarber indicates an expected call of ListServicesByBarber.
func (mr *MockServiceRepositoryMockRecorder) ListServicesByBarber(ctx, barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesByBarber", reflect.TypeOf((*MockServiceRepository)(nil).ListServicesByBarber), ctx, barberID)
}

// ProposeUpdate mocks base method.
func (m *MockServiceRepository) ProposeUpdate(ctx context.Context, shopID, barberID, serviceID string, in models.ServiceUpdateInput) (*models.ApprovalRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposeUpdate", ctx, shopID, barberID, serviceID, in)
	ret0, _ := ret[0].(*models.ApprovalRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProposeUpdate indicates an expected call of ProposeUpdate.
func (mr *MockServiceRepositoryMockRecorder) ProposeUpdate(ctx, shopID, barberID, serviceID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeUpdate", reflect.TypeOf((*MockServiceRepository)(nil).ProposeUpdate), ctx, shopID, barberID, serviceID, in)
}
