// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/shop_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/shop_repository.go -destination=internal/repository/mocks/shop_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "barbermanager/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShopRepository is a mock of ShopRepository interface.
type MockShopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepositoryMockRecorder
	isgomock struct{}
}

// MockShopRepositoryMockRecorder is the mock recorder for MockShopRepository.
type MockShopRepositoryMockRecorder struct {
	mock *MockShopRepository
}

// NewMockShopRepository creates a new mock instance.
func NewMockShopRepository(ctrl *gomock.Controller) *MockShopRepository {
	mock := &MockShopRepository{ctrl: ctrl}
	mock.recorder = &MockShopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopRepository) EXPECT() *MockShopRepositoryMockRecorder {
	return m.recorder
}

// CreateShop mocks base method.
func (m *MockShopRepository) CreateShop(ctx context.Context, in models.ShopCreateInput, ownerID string) (*models.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShop", ctx, in, ownerID)
	ret0, _ := ret[0].(*models.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShop indicates an expected call of CreateShop.
func (mr *MockShopRepositoryMockRecorder) CreateShop(ctx, in, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShop", reflect.TypeOf((*MockShopRepository)(nil).CreateShop), ctx, in, ownerID)
}

// GetShop mocks base method.
func (m *MockShopRepository) GetShop(ctx context.Context, id string) (*models.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShop", ctx, id)
	ret0, _ := ret[0].(*models.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShop indicates an expected call of GetShop.
func (mr *MockShopRepositoryMockRecorder) GetShop(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShop", reflect.TypeOf((*MockShopRepository)(nil).GetShop), ctx, id)
}

// GetShopHours mocks base method.
func (m *MockShopRepository) GetShopHours(ctx context.Context, shopID string) ([]models.ShopHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopHours", ctx, shopID)
	ret0, _ := ret[0].([]models.ShopHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopHours indicates an expected call of GetShopHours.
func (mr *MockShopRepositoryMockRecorder) GetShopHours(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopHours", reflect.TypeOf((*MockShopRepository)(nil).GetShopHours), ctx, shopID)
}

// ListShops mocks base method.
func (m *MockShopRepository) ListShops(ctx context.Context, city string) ([]models.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShops", ctx, city)
	ret0, _ := ret[0].([]models.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShops indicates an expected call of ListShops.
func (mr *MockShopRepositoryMockRecorder) ListShops(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShops", reflect.TypeOf((*MockShopRepository)(nil).ListShops), ctx, city)
}

// SetShopHours mocks base method.
func (m *MockShopRepository) SetShopHours(ctx context.Context, shopID string, hours []models.ShopHours) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShopHours", ctx, shopID, hours)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShopHours indicates an expected call of SetShopHours.
func (mr *MockShopRepositoryMockRecorder) SetShopHours(ctx, shopID, hours any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShopHours", reflect.TypeOf((*MockShopRepository)(nil).SetShopHours), ctx, shopID, hours)
}

// UpdateShop mocks base method.
func (m *MockShopRepository) UpdateShop(ctx context.Context, id string, in models.ShopUpdateInput) (*models.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShop", ctx, id, in)
	ret0, _ := ret[0].(*models.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShop indicates an expected call of UpdateShop.
func (mr *MockShopRepositoryMockRecorder) UpdateShop(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShop", reflect.TypeOf((*MockShopRepository)(nil).UpdateShop), ctx, id, in)
}
